name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Gradle Build Action
      # You may pin to the exact commit or the version.
      # uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
      uses: gradle/gradle-build-action@v2.9.0
      with:
        # Gradle version to use. If specified, this Gradle version will be downloaded, added to the PATH and used for invoking Gradle.
        gradle-version: 8.0.0
        cache-disabled: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --settings-file=settings.gradle build 

      
