name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Install the Android SDK + required packages explicitly
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug --stacktrace

      
