name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Install the Android SDK + required packages explicitly
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          packages: |
            platform-tools
            platforms;android-35
            build-tools;35.0.0

      # (Optional, usually not needed because the action accepts licenses)
      # - name: Accept Android SDK licenses
      #   run: yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # (Optional but recommended) Gradle build caching & config isolation
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug --stacktrace

      
